### ISSUE TITLE
Force darkmode as default 

### ISSUE THREAD

**Issue by mnmartinelli** [wymcg/simtricks#5]
Colors in simtricks are represented incorrectly in light mode. This can be fixed by forcing darkmode as default. Please see comparison images below:
<img width="495" alt="darkmode" src="https://github.com/wymcg/simtricks/assets/98068955/5524a87b-7471-4cb7-b97f-e2d62a508b17">
<img width="499" alt="lightmode" src="https://github.com/wymcg/simtricks/assets/98068955/b46c138e-b1cb-4e3a-8027-5b6232847c89">

**Comment by wymcg** [comment]
Resolved, thanks @mnmartinelli!
